cgrindel/rules_swift_package_manager

.bazelrc
.github/actions/build_and_test/action.yml
.github/workflows/ci.yml
bazel_versions.bzl
ci.bazelrc
shared.bazelrc

chore: initial CI implementation

---

gazelle/BUILD.bazel
gazelle/config.go
gazelle/internal/swiftbin/BUILD.bazel
gazelle/internal/swiftbin/swift_bin.go
gazelle/internal/swiftbin/swift_bin_test.go
gazelle/internal/swiftpkg/BUILD.bazel
gazelle/internal/swiftpkg/package_info.go
gazelle/internal/swiftpkg/package_info_test.go
gazelle/internal/swiftpkg/swift_package.go

- Implement `InitPackage()`, `DumpPackage()`, and `DescribePackage()` in`swiftbin.SwiftBin`.
- Implement `swiftpkg.NewPackageInfo()` to retrieve the dump JSON and parse into `swiftpkg.Manifest`.
Related to #8.

feat: retrieve package dump JSON and generate `swiftpkg.PackageInfo`

---

BUILD.bazel
README.md
WORKSPACE
docs/BUILD.bazel
docs/design/BUILD.bazel
docs/design/high-level.md
docs/faq.md

- Add `markdown_pkg` to Bazel packages with markdown files.
- Update `README.md` with quickstart, tips and tricks and future work.
- Add FAQ
- Refine high-level design doc.
Closes #76, #77.

chore: add `README.md`, `faq.md`, and `high-level.md`

---

gazelle/BUILD.bazel
gazelle/doc.go
gazelle/internal/jsonutils/BUILD.bazel
gazelle/internal/jsonutils/doc.go
gazelle/lang.go

chore: add some doc comments to Go code

---

.github/workflows/create_release.yml
README.md
release/BUILD.bazel
release/README.md
release/workspace_snippet.tmpl

feat: add release process

---

README.md

fix: move snippet markers in README.md

---

BUILD.bazel
WORKSPACE
gazelle/internal/spdump/target.go
gazelle/internal/spdump/target_dependency.go
gazelle/internal/swift/product.go
gazelle/update_repos.go
nogo_config.json

- Add `nogo`.
- Fix issues found by `nogo`.
Related to #123.

chore: add `nogo` code analysis checks

---

swiftpkg/tests/swiftpkg_build_files_tests.bzl

chore: add clang build file generation tests

---

release/BUILD.bazel

fix: fix release archive name

---

swiftpkg/internal/deps_indexes.bzl
swiftpkg/internal/pkginfo_target_deps.bzl
swiftpkg/tests/deps_indexes_tests.bzl

- Refactored the tests to be table driven.
Related to #231.
Related to #208.

chore: support resolving modules to multiple labels

---

swiftpkg/internal/deps_indexes.bzl
swiftpkg/internal/pkginfo_target_deps.bzl
swiftpkg/tests/deps_indexes_tests.bzl

- Rename `modules` to `modules_by_name`.
- Add `modules_by_label` to support lookup of modules by their primary Bazel label.
- Made `labels_for_module` public.
- Rename `resolve_module_labels` to `resolve_module`.
- Update `pkginfo_target_deps` to resolve the module, then retrieve the labels.
Related to #199.

chore: refactor `deps_indexes` separating module resolution from label resolution

---

.github/workflows/ci.yml
examples/soto_example/Tests/SotoTests/SotoTests.swift
go.mod
go.sum
go_deps.bzl
tools/generate_ci_workflow/internal/github/BUILD.bazel
tools/generate_ci_workflow/internal/github/workflow.go
tools/generate_ci_workflow/internal/github/workflow_test.go
tools/generate_ci_workflow/main.go

chore: update CI to process entire matrix if a single job fails

---

go.mod
go.sum
go_deps.bzl

Related to #243.
Related to #173.
Related to #255.

chore: update outstanding go deps

---

BUILD.bazel
deps.bzl
docs/BUILD.bazel
docs/README.md
docs/doc_infos.bzl
docs/internal_rules_and_macros_overview.md
docs/repository_rules_overview.md
docs/rules_and_macros_overview.md
swiftpkg/BUILD.bazel
swiftpkg/internal/BUILD.bazel

fix: fix deps and enable documentation generattion

---

go.mod
go.sum
go_deps.bzl

Related to #173.
Related to #278.

chore: update Go deps

---

swiftpkg/internal/deps_indexes.bzl
swiftpkg/tests/deps_indexes_tests.bzl

feat: add support for packages JSON in Starlark code

---

.bcr/config.yml
.bcr/metadata.template.json
.bcr/presubmit.yml
.bcr/source.template.json

chore: add files for `publish-to-bcr`

---

go.mod
go.sum
go_deps.bzl

Related to #282.
Related to #173.

chore(deps): update go dependencies

---

README.md
release/BUILD.bazel

fix: update workspace name in workspace snippet

---

.github/actions/configure_remote_cache_auth/action.yml
.github/workflows/ci.yml
.gitignore
release/archive_test_runner.sh
shared.bazelrc

- Configure to use remote cache.
- Fix bug in `archive_test_runner`.
Closes #338.

chore: configure to use remote cache

---

bzlmod/workspace/MODULE.bazel
examples/http_archive_ext_deps/MODULE.bazel
examples/interesting_deps/MODULE.bazel
examples/ios_sim/MODULE.bazel
examples/objc_code/MODULE.bazel
examples/phone_number_kit/MODULE.bazel
examples/pkg_manifest_minimal/MODULE.bazel
examples/resources_example/MODULE.bazel
examples/soto_example/MODULE.bazel
examples/tca_example/MODULE.bazel
examples/vapor_example/MODULE.bazel
examples/xcmetrics_example/MODULE.bazel

Upgrade rules_swift (1.8.0) and rules_apple (2.3.0)
Closes #327.

chore: upgrade rules_swift (1.8.0) and rules_apple (2.3.0)

---

.github/workflows/ci.yml
tools/generate_ci_workflow/internal/github/workflow.go

- Add `concurrency` section to the CI workflow.
- Update workflow tool to support concurrency.
- Add comments to the workflow structs.

chore: cancel previous workflows if pull request is updated

---

.github/renovate.json
MODULE.bazel.lock
do_renovate_post_upgrade

🤦‍♂️ I am jumping around too much today.

fix: actually use `do_renovate_post_upgrade` 

---

do_renovate_post_upgrade

fix: clang version in `do_renovate_post_upgrade`

---

examples/README.md
tools/create_example/BUILD.bazel
tools/create_example/create_example.sh
tools/create_example/template_files/.bazelrc
tools/create_example/template_files/BUILD.bazel
tools/create_example/template_files/MODULE.bazel
tools/create_example/template_files/README.md
tools/create_example/template_files/do_test
tools/create_example/template_files/set_up_clean_test

- Add `//tools/create_example` binary.
- Add `examples/README.md`.

chore: add utility to create an example workspace

---

examples/vapor_example/MODULE.bazel
examples/vapor_example/set_up_clean_test
examples/vapor_example/swift/BUILD.bazel
examples/vapor_example/swift/deps.bzl
gazelle/internal/swift/bzlmod.go
gazelle/internal/swift/bzlmod_test.go
gazelle/update_repos.go

Fixes https://github.com/cgrindel/rules_swift_package_manager/issues/553 
The stanza template should account for deps index path.

fix: bzlmod deps_index custom path

---

config_settings/bazel/apple_platform_type/apple_platform_types.bzl

chore: add visionos to apple_platform_types

---

shared.bazelrc

[BCR presubmit failure](https://buildkite.com/bazel/bcr-presubmit/builds/2306#018b6856-fd5e-4b6a-8a84-a0360fd7d6aa)

fix: revert experimental flag change to fix BCR presubmit

---

gazelle/internal/swift/is_builtin_module.go

Adds support for built-in frameworks like [RegexBuilder](https://developer.apple.com/documentation/regexbuilder).

feat: Add support RegexBuilder built-in framework

---

examples/tca_example/README.md
examples/tca_example/Sources/App.swift

* rewrite readme, which was incorrectly copied over from the Firebase example
* update the example app to reflect the latest state from https://github.com/pointfreeco/swift-composable-architecture#basic-usage
* use macros from the example app
~This will require https://github.com/cgrindel/rules_swift_package_manager/pull/747 to pass CI.~

chore: update TCA example

---

.github/workflows/ci.yml
tools/generate_ci_workflow/internal/github/workflow.go
tools/generate_ci_workflow/internal/github/workflow_test.go

chore: add `merge_group` to CI workflow

---

examples/http_archive_ext_deps/WORKSPACE
examples/vapor_example/WORKSPACE
release/workspace_snippet.tmpl

Related to https://github.com/cgrindel/rules_swift_package_manager/issues/846.

fix: invalid go version errors in CI

---

examples/vapor_example/MODULE.bazel.lock
examples/vapor_example/swift/Package.resolved
examples/vapor_example/swift/Package.swift
examples/vapor_example/swift/deps.bzl
examples/vapor_example/swift/deps_index.json

chore: upgrade vapor and fluent

---

docs/faq.md

docs: update the order for the spawn strategy when using rules_xcodeproj

---

README.md

chore: README.md typo

---

examples/firebase_example/MODULE.bazel
examples/ios_sim/MODULE.bazel

Needed to support rules_swift 2.0+.

chore(deps): Update rules_xcodeproj to 2.5.1

---

bzlmod/workspace/MODULE.bazel
bzlmod/workspace/Package.swift
deps.bzl
examples/firebase_example/MODULE.bazel
examples/google_maps_example/MODULE.bazel
examples/grpc_example/MODULE.bazel
examples/grpc_package_example/MODULE.bazel
examples/interesting_deps/MODULE.bazel
examples/ios_sim/MODULE.bazel
examples/lottie_ios_example/MODULE.bazel
examples/messagekit_example/MODULE.bazel
examples/nimble_example/MODULE.bazel
examples/objc_code/MODULE.bazel
examples/phone_number_kit/MODULE.bazel
examples/pkg_manifest_minimal/MODULE.bazel
examples/pkg_manifest_minimal/Package.swift
examples/resources_example/MODULE.bazel
examples/shake_ios_example/MODULE.bazel
examples/snapkit_example/MODULE.bazel
examples/soto_example/MODULE.bazel
examples/stripe_example/MODULE.bazel
examples/stripe_example/Package.swift
examples/symlink_example/MODULE.bazel
examples/tca_example/MODULE.bazel
examples/tca_example/Package.swift
examples/vapor_example/MODULE.bazel
examples/xcmetrics_example/MODULE.bazel
tools/create_example/template_files/MODULE.bazel

- #1170 
- #1175 
- #1177 
- #1178 
- #1180

chore: catch up on stuck upgrades

---

do_renovate_post_upgrade

chore: remove debug code

---

swiftpkg/internal/artifact_infos.bzl
swiftpkg/internal/swiftpkg_build_files.bzl

chore: fix typo artifiact to artifact

---

swiftpkg/internal/pkginfo_target_deps.bzl

Our behavior matches SPM's behavior.

chore: remove invalid comment

---

do_renovate_post_upgrade

Debug why update_swift_packages is not being called.

chore: add debug code to do_renovate_post_upgrade

---

.github/workflows/ci.yml
examples/firebase_example/MODULE.bazel
examples/google_maps_example/MODULE.bazel
examples/interesting_deps/MODULE.bazel
examples/ios_sim/MODULE.bazel
examples/lottie_ios_example/MODULE.bazel
examples/messagekit_example/MODULE.bazel
examples/nimble_example/MODULE.bazel
examples/objc_code/MODULE.bazel
examples/phone_number_kit/MODULE.bazel
examples/resources_example/MODULE.bazel
examples/shake_ios_example/MODULE.bazel
examples/skip_local_transitive_dependencies_example/MODULE.bazel
examples/snapkit_example/MODULE.bazel
examples/soto_example/MODULE.bazel
examples/stripe_example/MODULE.bazel
examples/swift_package_registry_example/MODULE.bazel
examples/symlink_example/MODULE.bazel
examples/tca_example/MODULE.bazel
examples/vapor_example/MODULE.bazel
examples/xcmetrics_example/MODULE.bazel

fix: failing UI tests when run on Xcode 16.3 (upgrade to `rules_apple` 3.21.0)
