cgrindel/rules_swift_package_manager

- BUILD.bazel
- WORKSPACE
- examples/simple/.bazelrc
- gazelle/internal/spdesc/BUILD.bazel
- gazelle/internal/spdesc/manifest.go
- gazelle/internal/spdesc/manifest_test.go
- gazelle/internal/spdump/BUILD.bazel
- gazelle/internal/spdump/manifest.go
- gazelle/internal/spdump/manifest_test.go
- gazelle/internal/swiftpkg/BUILD.bazel
- gazelle/internal/swiftpkg/package_info.go
- gazelle/internal/swiftpkg/package_info_test.go
- go.sum
- go_deps.bzl
- Moved dump manifest models to `spdump`.
- Implemented `spdesc` with the describe models
- Add describe models to `swiftpkg.PackageInfo`.
Related to #8
> feat: retrieve package description and incorporate into `swiftpkg.PackageInfo`

- .github/workflows/ci.yml
Ensure that job status from dependent jobs propagates.
> chore: use `gha_join_jobs` for `all_ci_tests`

- .github/actions/build_and_test/action.yml
- BUILD.bazel
- WORKSPACE
- deps.bzl
- Upgrade `bazel-starlib` to 0.9.0.
- Use `tidy` from `bzltidy`.
Closes #26.
> chore: upgrade `bazel-starlib` and use `bzltidy`

- examples/BUILD.bazel
- examples/pkg_manifest/BUILD.bazel
- examples/pkg_manifest_test_runner.sh
- gazelle/internal/jsonutils/json_map.go
- gazelle/internal/jsonutils/json_map_test.go
- gazelle/internal/spreso/BUILD.bazel
- gazelle/internal/spreso/pin.go
- gazelle/internal/spreso/pin_test.go
- Add `jsonutils.IntAtKey()`
- Add `spreso.NewPinsFromResolvedPackageJSON()` to parse JSON and return the pins. 
Related to #9.
> feat: parse resolve package JSON and return pins

- swiftpkg/internal/lists.bzl
- swiftpkg/internal/swift_package.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/lists_tests.bzl
- Update `swift_package` to generate a single `swift_binary` declaratio for executable targets.
- Add `lists.contains()`.
- Document `lists`.
Related to #9.
> chore(`swift_package`): ensure executable targets create a single `swift_binary`

- gazelle/config.go
- gazelle/generate.go
- gazelle/internal/spdump/BUILD.bazel
- gazelle/internal/spdump/dependency.go
- gazelle/internal/spdump/manifest.go
- gazelle/internal/spdump/manifest_test.go
- gazelle/internal/swift/BUILD.bazel
- gazelle/internal/swift/bazel_label.go
- gazelle/internal/swift/bazel_label_test.go
- gazelle/internal/swift/rules_from_manifest.go
- gazelle/internal/swiftcfg/BUILD.bazel
- gazelle/internal/swiftcfg/swift_config.go
- gazelle/internal/swiftcfg/swift_config_test.go
- gazelle/internal/swiftpkg/BUILD.bazel
- gazelle/internal/swiftpkg/dependency.go
- gazelle/internal/swiftpkg/exported_targets.go
- gazelle/internal/swiftpkg/package_info.go
- gazelle/internal/swiftpkg/package_info_test.go
- gazelle/internal/swiftpkg/platform.go
- gazelle/internal/swiftpkg/product.go
- gazelle/internal/swiftpkg/target.go
- gazelle/internal/swiftpkg/target_dependency.go
- gazelle/update_repos.go
- go.mod
- go.sum
- go_deps.bzl
- Introduce package info models in `swiftpkg`.
- Switch to use new models.
Closes #61.
> chore: migrate to `swiftpkg` models

- examples/http_archive_ext_deps/set_up_clean_test
- examples/http_archive_ext_deps_test_runner.sh
- examples/pkg_manifest_minimal/set_up_clean_test
- examples/pkg_manifest_minimal_test_runner.sh
- Add `set_up_clean_test` bash script to each workspace with logic for removing BUILD.bazel files and setting up minimal, runnable conditions.
- Update the test runners call perform a test with the code as it is checked-in and to do a clean test.
Closes #69.
> chore: add clean test for each example workspace

- .bazelrc
- examples/pkg_manifest_minimal/BUILD.bazel
- examples/pkg_manifest_minimal/Package.resolved
- examples/pkg_manifest_minimal/Package.swift
- examples/pkg_manifest_minimal/do_test
- examples/pkg_manifest_minimal/module_index.json
- examples/pkg_manifest_minimal/set_up_clean_test
- examples/pkg_manifest_minimal/swift_deps.bzl
- examples/pkg_manifest_minimal_test_runner.sh
- gazelle/internal/spdump/target.go
- gazelle/internal/spdump/target_dependency.go
- gazelle/internal/swiftbin/swift_bin.go
- gazelle/internal/swiftpkg/dependency.go
- gazelle/internal/swiftpkg/target.go
- gazelle/internal/swiftpkg/target_dependency.go
- gazelle/update_repos.go
- swiftpkg/internal/pkginfo_target_deps.bzl
- swiftpkg/internal/pkginfos.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/pkginfo_target_deps_tests.bzl
- swiftpkg/tests/pkginfos_tests.bzl
- swiftpkg/tests/swiftpkg_build_files_for_old_style_pkg_tests.bzl
- Add support for `target` reference. This is different from `byName`.
- Renamed `pkginfos.new_target_reference` to `pkginfos.new_by_name_reference`.
- Add SwiftFormat to the `pkg_manifest_minimal` example.
- Include `SWIFT_PACKAGE` directive when defining targets from `swift_package`.
Related to #52.
Related to #46.
> feat: add support for `target` references and `plugin` targets

- gazelle/BUILD.bazel
- gazelle/generate.go
- gazelle/internal/pathdistance/BUILD.bazel
- gazelle/internal/pathdistance/pathdistance.go
- gazelle/internal/stringslices/contains.go
- gazelle/internal/stringslices/contains_test.go
- gazelle/kinds.go
- gazelle/lang.go
- gazelle/resolve.go
- go.mod
- go.sum
- go_deps.bzl
- Ensure that obsolete Swift targets are removed if no srcs match.
- Add `deps` to list of attributes to be merged after dependency resolution.
- Remove `golang.org/x/exp/slices`.
Closes #70.
> fix: ensure `deps` are properly updated if a dependency disappears from the target

- examples/http_archive_ext_deps/WORKSPACE
- examples/pkg_manifest_minimal/Sources/MyExecutable/BUILD.bazel
- examples/pkg_manifest_minimal/module_index.json
- gazelle/internal/swift/bazel_label.go
- gazelle/internal/swift/bazel_label_test.go
- swiftpkg/internal/pkginfo_targets.bzl
- swiftpkg/internal/swift_package.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/pkginfo_targets_tests.bzl
- swiftpkg/tests/swiftpkg_build_files_for_old_style_pkg_tests.bzl
- Swift package targets are now generated with label names derived from their path and target name.
- All declarations for an external Swift package are generated in a single Bazel build file.
Related to #81.
> chore: create a single Bazel build file for each external Swift package

- examples/pkg_manifest_minimal/do_test
- examples/pkg_manifest_minimal/module_index.json
- examples/pkg_manifest_minimal/third_party/my_local_package/Package.swift
- examples/pkg_manifest_minimal/third_party/my_local_package/Sources/GreetingsFramework/EveningGreeting.swift
- examples/pkg_manifest_minimal/third_party/my_local_package/Sources/GreetingsFramework/WithName.swift
- examples/pkg_manifest_minimal/third_party/my_local_package/Sources/PrintGreeting/main.swift
- examples/pkg_manifest_minimal/third_party/my_local_package/Tests/GreetingsFrameworkTests/EveningGreetingTests.swift
- examples/pkg_manifest_minimal/third_party/my_local_package/Tests/GreetingsFrameworkTests/WithNameTests.swift
- swiftpkg/internal/swiftpkg_build_files.bzl
- Add `print-greeting` product to `my_local_package`.
- Update `do_test` in `pkg_manifest_minimal` to call `print-greeting`.
Related to #52.
> chore: add example of Swift executable product pre-5.4

- gazelle/internal/spdump/manifest_test.go
- gazelle/internal/spdump/target_dependency.go
- gazelle/internal/spdump/target_dependency_test.go
- gazelle/internal/spdump/target_test.go
- gazelle/internal/swiftpkg/target_dependency.go
> chore: rename `TargetName` to `Name` in `ByNameReference`

- gazelle/internal/spdump/manifest_test.go
- gazelle/internal/spdump/target.go
- gazelle/internal/spdump/target_test.go
- gazelle/internal/swiftpkg/target.go
- swiftpkg/internal/clang_files.bzl
- swiftpkg/internal/pkginfos.bzl
- swiftpkg/internal/repo_rules.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/pkginfos_tests.bzl
- swiftpkg/tests/swiftpkg_build_files_for_old_style_pkg_tests.bzl
- Separate headers between public and private.
- Combine headers found by inspection with those in the modulemap.
- Add support for custom defines for Swift and clang.
Related to #50.
> chore: address issues getting `vapor_example` working

- bazel_versions.bzl
- examples/http_archive_ext_deps/Sources/PrintStuff/BUILD.bazel
- examples/http_archive_ext_deps/Tests/MyDequeModuleTests/BUILD.bazel
- examples/http_archive_ext_deps/Tests/MyDequeModuleTests/CreateTests.swift
- examples/http_archive_ext_deps/Tests/MyDequeModuleTests/main.swift
- examples/http_archive_ext_deps/WORKSPACE
- examples/pkg_manifest_minimal/Sources/MyExecutable/BUILD.bazel
- examples/pkg_manifest_minimal/Tests/MyLibraryTests/BUILD.bazel
- examples/pkg_manifest_minimal/Tests/MyLibraryTests/MyLibraryTests.swift
- examples/pkg_manifest_minimal/Tests/MyLibraryTests/main.swift
- examples/pkg_manifest_minimal/WORKSPACE
- examples/pkg_manifest_minimal/module_index.json
- examples/vapor_example/Tests/AppTests/AppTests.swift
- examples/vapor_example/Tests/AppTests/BUILD.bazel
- examples/vapor_example/Tests/AppTests/main.swift
- examples/vapor_example/WORKSPACE
- gazelle/internal/swift/file_info.go
- gazelle/internal/swift/file_info_test.go
- gazelle/internal/swift/rules_common.go
- gazelle/internal/swift/rules_from_srcs.go
- Add support for `main.swift` in test packages.
- Add missing `main.swift` to `swift_test` for Linux.
- Remove 7.0-pre from supported Bazel versions to speed up CI.
Closes #89.
> chore: upgrade `rules_swift` to 1.5

- README.md
- docs/BUILD.bazel
- docs/README.md
- docs/repository_rules_overview.md
- swiftpkg/BUILD.bazel
- swiftpkg/internal/BUILD.bazel
- swiftpkg/internal/local_swift_package.bzl
- swiftpkg/internal/repo_rules.bzl
- swiftpkg/internal/swift_package.bzl
> chore: generate Starlark documentation

- deps.bzl
- examples/BUILD.bazel
Goal: Speed up CI while ensuring that each example is executed at least once under the current Bazel version.
> chore: reduce the number of integration test permutations

- README.md
- docs/design/high-level.md
- docs/faq.md
- Add CI badge to the `README.md`.
- Update docs.
Related to #107.
> chore: prepare for initial release

- README.md
- docs/BUILD.bazel
- docs/faq.md
- examples/interesting_deps/BUILD.bazel
- examples/interesting_deps/set_up_clean_test
- examples/ios_sim/BUILD.bazel
- examples/ios_sim/set_up_clean_test
- examples/objc_code/BUILD.bazel
- examples/objc_code/set_up_clean_test
- examples/pkg_manifest_minimal/BUILD.bazel
- examples/pkg_manifest_minimal/Package.resolved
- examples/pkg_manifest_minimal/set_up_clean_test
- examples/vapor_example/BUILD.bazel
- examples/vapor_example/set_up_clean_test
- examples/xcmetrics_example/BUILD.bazel
- examples/xcmetrics_example/set_up_clean_test
- gazelle/config.go
- gazelle/internal/swiftbin/swift_bin.go
- gazelle/internal/swiftbin/swift_bin_test.go
- gazelle/internal/swiftcfg/swift_config.go
- gazelle/update_repos.go
- swiftpkg/BUILD.bazel
- swiftpkg/defs.bzl
- swiftpkg/internal/BUILD.bazel
- swiftpkg/internal/swift_update_packages.bzl
- Add `swift_update_packages_to_latest` flag to Gazelle extension. When enabled, it runs `swift package update` instead of `swift package resolve` during `update-repos`.
- Introduce `swift_update_packages` macro to define variants of the `gazelle` declaration for `update-repos`. One performs the resolve and the other the update.
Closes #137.
> feat: introduce `swift_update_packages` macro

- examples/firebase_example/.bazelrc
- examples/firebase_example/WORKSPACE
- swiftpkg/internal/clang_files.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/clang_files_tests.bzl
- Detect all Bazel supported header files.
- Fix the workspace name of the firebase example.
- Add flags to `.bazelrc` that are required for the firebase example.
Related to #153.
> feat: detect all Bazel header file types and other fixes

- examples/firebase_example/.bazelrc
- swiftpkg/internal/clang_files.bzl
- swiftpkg/internal/pkginfo_target_deps.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- Adding the recursive list of header paths caused compilation issues building [firebase/abseil-cpp-SwiftPM](https://github.com/firebase/abseil-cpp-SwiftPM).
- Fixed bug with header identification not using the supported list of headers.
- Fixed bug in fail call.
Related to #153.
> fix: remove inappropriate inclusion of public header directories

- config_settings/platform_type/BUILD.bazel
- swiftpkg/internal/build_decls.bzl
- swiftpkg/internal/pkginfos.bzl
- swiftpkg/internal/starlark_codegen.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/pkginfos_tests.bzl
- Refactor how build settings are read and stored. This provides a means for supporting conditions on the build settings.
- Added some missing documentation.
- Add `//config_settings/platform_types` that will be used for platform name conditions.
Related to #153.
> chore: refactor build settings to support conditions

- swiftpkg/internal/build_decls.bzl
- swiftpkg/internal/starlark_codegen.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/build_decls_tests.bzl
- swiftpkg/tests/starlark_codegen_tests.bzl
- Moved function call Starlark codegen to `starlark_codegen` module.
- Add missing documentation.
Related to #153
> feat: support expressions and operators in Starlark code generation

- swiftpkg/internal/bzl_selects.bzl
- swiftpkg/internal/pkginfos.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/bzl_selects_tests.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
- Add conditional support for `headerSearchPaths`.
- Add conditional support for `unsafeFlags`.
- Refactor tests for `swiftpkg_build_files`.
Related to #153.
> feat: finish adding conditional build setting support

- swiftpkg/tests/swiftpkg_build_files_tests.bzl
- Renamed existing test data to describe better what it represents.
- Add an example of executable product referencing an executable target.
- Add an example with `define` and `unsafeFlags` settings for a Swift target.
- Add an example of a Swift library that uses `XCTest` should be marked `testonly = True`.
Related to #177.
> chore: add unit tests for additional Swift target/product use cases

- config_settings/spm/platform/platforms.bzl
- swiftpkg/internal/bzl_selects.bzl
- swiftpkg/internal/pkginfo_target_deps.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/bzl_selects_tests.bzl
- Values for the same condition can be found in multiple entries. Update `bzl_selects.to_starlark` to collect the values.
- Ensure generated `apple_dynamic_xcframework_import` declarations are publicly visible.
Related to #153
> fix: ensure `bzl_selects.to_starlark` collects condition values

- README.md
- WORKSPACE
- deps.bzl
- docs/faq.md
- Upgrade bazel-skylib to 0.12.1. 
- Add workaround for missing strict dep when building markdown toc generator.
The workaround should fix the strict dep failure seen in CI runs for #205.
> chore: upgrade bazel-starlib to 0.12.1

- BUILD.bazel
- examples/pkg_manifest_minimal/do_test
- gazelle/BUILD.bazel
- gazelle/config.go
- gazelle/internal/reslog/BUILD.bazel
- gazelle/internal/reslog/resolution_logger.go
- gazelle/internal/reslog/resolution_logger_test.go
- gazelle/internal/reslog/rule_resolution.go
- gazelle/internal/reslog/rule_resolution_summary.go
- gazelle/internal/reslog/rule_resolution_test.go
- gazelle/internal/swiftcfg/BUILD.bazel
- gazelle/internal/swiftcfg/swift_config.go
- gazelle/resolve.go
- go.mod
- go.sum
- go_deps.bzl
If enabled, it creates a YAML file with records describing the resolution process for each evaluated rule.
Execute by passing the `--resolution_log` flag:
```sh
$ bazel run //:update_build_files -- "--resolution_log=${PWD}/res_log.yml"
```
Don't forget to specify `${PWD}` or an absolute path. Otherwise, the log file will be written to the runfiles directory.
Related to #202.
> feat: add resolution logger to Gazelle extension

- examples/firebase_example/appdistribution/AppDistributionExample/BUILD.bazel
Ran `//:tidy` in firebase example.
Closes #202.
> fix: update firebase example with correct deps

- swiftpkg/internal/repo_rules.bzl
Test-only Targets:
- Those of type `test`.
- Targets that have no product memberships.
Related to #231.
> fix: exclude test-only SPM targets when generating Bazel targets

- swiftpkg/internal/deps_indexes.bzl
- swiftpkg/internal/pkginfo_target_deps.bzl
- swiftpkg/tests/deps_indexes_tests.bzl
- swiftpkg/tests/pkginfo_target_deps_tests.bzl
- Add support for product resolution in `deps_indexes`.
- Update `pkginfo_target_deps` to resolve byName references in the following priority:
1. Module in the same repo.
2. Product with the specified name.
3. Any module with the specified name.
Closes #199.
> fix: change `byName` resolution logic

- .github/actions/set_up_macos/action.yml
- .github/actions/test_example/action.yml
- .github/workflows/ci.yml
> chore: set up matrix strategy for CI

- README.md
The plugin is not required for the `swift_bazel` Gazelle plugin. The example workspaces do use the Skylib Gazelle plugin, if clients would like to see how to specify multiple plugins.
Closes #247.
> fix: remove reference to the Skylib Gazelle plugin from the README.md

- BUILD.bazel
- docs/rules_and_macros_overview.md
- examples/pkg_manifest_minimal/BUILD.bazel
- examples/pkg_manifest_minimal/MODULE.bazel
- gazelle/BUILD.bazel
- gazelle/config.go
- gazelle/internal/swift/BUILD.bazel
- gazelle/internal/swift/bzlmod.go
- gazelle/internal/swift/bzlmod_test.go
- gazelle/internal/swift/dependency_index.go
- gazelle/internal/swift/dependency_index_test.go
- gazelle/internal/swiftcfg/swift_config.go
- gazelle/internal/updmarker/BUILD.bazel
- gazelle/internal/updmarker/updater.go
- gazelle/internal/updmarker/updater_test.go
- gazelle/update_repos.go
- shared.bazelrc
- swiftpkg/internal/swift_update_packages.bzl
- Add `-print_bzlmod_stanzas` flag to `update-repos`. Enabling the option will print the relevant stanzas to stdout.
- Add `-update_bzlmod_stanzas` flag to `update-repos`. Enabling the option will add/update the stanzas to `MODULE.bazel`. NOTE: This mechanism is very rudimentary using comment markers to identify what to replace. A [design doc for a better solution](https://docs.google.com/document/d/1dj8SN5L6nwhNOufNqjBhYkk5f-BJI_FPYWKxlB3GAmA/edit?usp=sharing) has been submitted for review by @fmeum.
Related to #276
> feat: provide options for printing and updating bzlmod stanzas in `MODULE.bazel`

- .bcr/presubmit.yml
Only test on macos for now as the Ubuntu runner does not have Swift installed.
Related to #322.
> fix: update BCR presubmit to only run on MacOS

- .github/workflows/ci.yml
- .github/workflows/commit_msg_check.yml
- Use `agenthunt/conventional-commit-checker-action@v1.0.0` to check commit message.
Closes #340.
> chore: add conventional commit check

- .github/workflows/ci.yml
Addresses warning:
```
[tidy_and_test_matrix (macos-12, true)](https://github.com/cgrindel/rules_swift_package_manager/actions/runs/4645768179/jobs/8222718514#step:7:2)
Unexpected input(s) 'github_token', valid inputs are ['']
```
> fix: remove extraneous arg to tidy_and_test

- docs/repository_rules_overview.md
- gazelle/internal/swift/repo_rule_from_bazel_repo.go
- gazelle/internal/swift/repo_rule_from_bazel_repo_test.go
- gazelle/update_repos.go
- swiftpkg/internal/local_swift_package.bzl
This fixes the relative path resolution for local_swift_package when the Package.swift is not in the root of the repository.
Closes #363
> fix: local_swift_package relative path resolution

- README.md
- docs/patch_swift_package.md
- Remove some garbage text at the end of the URL.
- Fix patch doc table formatting.
> fix: correct typo linking to patch doc

- .github/workflows/ci.yml
- BUILD.bazel
- MODULE.bazel
- deps.bzl
- examples/example_infos.bzl
- examples/http_archive_ext_deps/.bazelrc
- examples/http_archive_ext_deps/WORKSPACE
- Upgrade `rules_go` to 0.39.1.
- Replace references to `@go_sdk//:bin/go` with `@io_bazel_rules_go//go`.
- Sync'd dependency versions between `WORKSPACE` and `MODULE.bazel`.
Closes #408.
cc: @fmeum
> chore: upgrade to rules_go 0.39.1 and remove references to go_sdk

- gazelle/lang.go
- Implement `ApparentLoads()`.
- Replace `Loads()` implementation with a panic.
Closes #326.
> chore: implement `ModuleAwareLanguage`

- shared.bazelrc
- Ensure that BES is uploaded async by default.
- Disable BES upload for `run`.
> chore: optimize BES upload

- swiftpkg/internal/pkginfo_targets.bzl
- swiftpkg/internal/pkginfos.bzl
- swiftpkg/tests/BUILD.bazel
- swiftpkg/tests/pkginfo_target_deps_tests.bzl
- swiftpkg/tests/pkginfo_targets_tests.bzl
- swiftpkg/tests/pkginfos_tests.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
- swiftpkg/tests/testutils.bzl
- Add `label` to target.
- Add `pkginfo_targets.get_by_label()`.
- Pass `repository_ctx` to `pkginfos.new_from_parsed_json()`.
- Add `swift_src_info` with `has_objv_directive`.
- Add `testutils` module.
- Update tests to use mangled repository name when retrieve `repository_ctx.name`.
Related to #425.
> chore: add `label` to target

- swiftpkg/internal/repository_utils.bzl
- Add the `return_code` to the error message sent to stderr.
> chore: show the return code when an SPM command fails

- do_renovate_post_upgrade
The shell script sets the appropriate environment variables and passes the correct flags.
> chore: use shell script to execute tidy_modified

- do_renovate_post_upgrade
We need clang for Bazel and rules_swift to work properly.
> chore: install clang in `do_renovate_post_upgrade`

- .github/workflows/ci.yml
- examples/BUILD.bazel
- examples/example_infos.bzl
- examples/test_runner.sh
- shared.bazelrc
- tools/generate_ci_workflow/internal/github/workflow.go
- tools/generate_ci_workflow/internal/testparams/int_test_params.go
- tools/generate_ci_workflow/internal/testparams/int_test_params_test.go
- tools/generate_ci_workflow/main.go
- Remove the content of `WORKSPACE`.
- Rework Bazel integration tests so that legacy (non-bzlmod) tests are listed as targets.
- Update the CI workflow to not include `enable_bzlmod`.
> chore: remove legacy WORKSPACE

- swiftpkg/internal/swiftpkg_build_files.bzl
Previously, binary targets were exposed using `apple_dynamic_xcframework_import`. Now, they will be exposed as `apple_statix_xcframework_import`. 
If anyone wishes to be able control how these targets are represented in the Bazel build graph, please comment on #559.
Closes #498.
> fix: use `apple_static_xcframework_import` for `binaryTarget` in SPM

- bzlmod/workspace/Sources/MyLibrary/BUILD.bazel
- examples/http_archive_ext_deps/Sources/MyDequeModule/BUILD.bazel
- examples/ios_sim/Sources/Foo/BUILD.bazel
- examples/nimble_example/Sources/NimbleExample/BUILD.bazel
- examples/nimble_example/swift_deps_index.json
- examples/pkg_manifest_minimal/Sources/MyLibrary/BUILD.bazel
- examples/tca_example/SwiftUICaseStudies/04-HigherOrderReducers-ResuableOfflineDownloads/BUILD.bazel
- examples/tca_example/SwiftUICaseStudies/Internal/BUILD.bazel
- examples/vapor_example/Sources/App/BUILD.bazel
- examples/xcmetrics_example/Package.resolved
- examples/xcmetrics_example/swift_deps_index.json
- gazelle/internal/swift/rules_common.go
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
[Background info](https://github.com/bazelbuild/rules_apple/issues/1939#issuecomment-1495175316)
In short, let the leaf nodes of the build graph pass along the appropriate configuration values when building `swift_library` targets. This PR makes this change for declarations for external Swift packages and for Gazelle generated build files.
Closes #339.
> chore: mark `swift_library` declarations as manual

- swiftpkg/internal/pkginfos.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/pkginfos_tests.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
- swiftpkg/tests/testutils.bzl
It turns out that the auto-discovered Swift package resources (#576) are listed in the description JSON. This PR ended up removing the auto-discovery code and having each resource listed as a file path.
Updated the `testutils` to support stub calls to `repository_files.is_directory()`.
Closes #575.
> chore: refactor how resources are specified on `apple_resource_bundle`

- swiftpkg/internal/clang_files.bzl
Fixes the issue raised in https://github.com/cgrindel/rules_swift_package_manager/issues/510
In the specific case of Sentry (https://github.com/getsentry/sentry-cocoa), the generated `objc_library` target for the main `Sentry` module included the right headers, allowing it to build, but not the right sources (for instance https://github.com/getsentry/sentry-cocoa/blob/72c8d84c86cebd726dd3b34ab9ff09a3596dd5f2/Sources/Sentry/SentrySamplingProfiler.cpp#L169). This cause the build to work but not the link.
> fix: allow .cpp when listing C++ files

- examples/interesting_deps/BUILD.bazel
- examples/interesting_deps/MODULE.bazel
- examples/interesting_deps/Package.resolved
- examples/interesting_deps/Package.swift
- examples/interesting_deps/main.swift
- examples/interesting_deps/simple_test.sh
- examples/interesting_deps/swift_deps_index.json
- swiftpkg/internal/clang_files.bzl
- swiftpkg/internal/pkginfos.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/clang_files_tests.bzl
- Add a trailing slash to the exclude paths passed to `repository_files.list_files_under()`. This was preventing the exclude logic from working properly.
- Escape spaces in paths added to clang include paths via `-I`.
- SPM automatically detects certain directory names (e.g. `include`, `public`) for clang targets and uses them as public header directories. Added code ensuring that these magical header directories are added to public header directory list.
- Add [CocoaLumberjack](https://github.com/CocoaLumberjack/CocoaLumberjack) to the `interesting_deps` example.
Closes #617.
> fix: several issues preventing CocoaLumberjack from working

- swiftpkg/internal/objc_files.bzl
- swiftpkg/tests/objc_files_tests.bzl
The [Sentry package](https://github.com/getsentry/sentry-cocoa) uses [an unusual import syntax for the SystemConfiguration framework](https://github.com/getsentry/sentry-cocoa/blob/e32423038e99f0c5d868744421d664cdd55c7383/Sources/Sentry/include/SentryReachability.h#L31):
```objc
```
This PR updates the parsing logic for `#import` lines to support whitespace between the `#` and the `import`.
Related to #510.
> fix: support `#import` with whitespace between `#` and `import`

- gazelle/internal/spdump/dependency.go
In Xcode 15 / Swift 5.9 Apple changed the output format of `swift package dump-package` which rules_swift_package_manager parsed. This caused the JSON deserialization to fail.
Specifically, the SourceControlLocation type changed from a single RemoteLocation to an array of RemoteLocation(s) and these are now objects with the key "urlString" instead of "url".
I added support for both the Xcode 14 / Swift 5.8 format as well as the new Xcode 15 / Swift 5.9 format.
Whenever we drop support for Xcode 14, the support for the old format can be removed.
I verified the change from my repo by using a local_path_override with this patch and I verified that before swift_update_packages failed with the error:
```
gazelle: index 0 expected to be type 'string', but was type 'map[string]interface {}'
``` …
> fix: Handle Xcode 15 swift package format

- examples/pkg_manifest_minimal/BUILD.bazel
- examples/pkg_manifest_minimal/Sources/MyLibrary/BUILD.bazel
- gazelle/config.go
- gazelle/generate.go
- gazelle/internal/swift/rules_common.go
- gazelle/internal/swift/rules_from_protos.go
- gazelle/internal/swift/rules_from_srcs.go
- gazelle/internal/swiftcfg/swift_config.go
This PR introduces a directive to disable the addition of the manual tag to generated swift_library targets.
I understand the intent behind the tag and am ok with keeping it the default. But for more advanced users who understand that they need to pass the apple platform type configuration, it is useful to be able to build globs of these targets without a dedicated build test target.
> feat: Add directive to disable manual tag

- swiftpkg/internal/pkginfos.bzl
- swiftpkg/internal/repository_files.bzl
- Instead of shelling out to test each path, the new code finds all of the directories under the target in one shell call. The result is then added to a set and the set is checked.
- The starlark profile for the `soto_example` dropped from 350 seconds to 46 seconds.
- Simplified the implementation for `repository_files.is_directory()`.
Closes #582.
> chore(perf): refactor checking path for directory

- examples/firebase_example/.bazelrc
- examples/firebase_example/swift_deps_index.json
- examples/soto_example/.bazelrc
- examples/soto_example/swift_deps_index.json
- examples/vapor_example/.bazelrc
- examples/vapor_example/swift/deps_index.json
- examples/xcmetrics_example/.bazelrc
- examples/xcmetrics_example/swift_deps_index.json
- gazelle/internal/spdump/manifest.go
- gazelle/internal/spdump/manifest_test.go
- gazelle/internal/swift/dependency_index.go
- gazelle/internal/swift/package.go
- gazelle/internal/swiftpkg/package_info.go
- gazelle/update_repos.go
- Include the `cLanguageStandard` and `cxxLanguageStandard` settings in the Swift dependency index JSON.
- Print suggested Bazel flags based upon the language standard settings.
Related to #510.
> feat: print suggested Bazel flags based on package language standard settings

- swiftpkg/internal/pkginfos.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
This fixes the `swift-atomics` package.
> feat: add support for `.enableExperimentalFeature()`

- config_settings/spm/platform/platforms.bzl
- examples/interesting_deps/BUILD.bazel
- examples/interesting_deps/MODULE.bazel
- examples/interesting_deps/Package.resolved
- examples/interesting_deps/Package.swift
- examples/interesting_deps/main.swift
- examples/interesting_deps/swift_deps_index.json
- Add mapping for `driverkit` treating it as a `macos` platform.
- Add [OpenCombine package](https://github.com/OpenCombine/OpenCombine) to the `interesting_deps` example. It references `driverkit`.
Closes #379.
> chore: add mapping for driverkit

- examples/interesting_deps/.bazelrc
- examples/interesting_deps/BUILD.bazel
- examples/interesting_deps/MODULE.bazel
- examples/interesting_deps/Package.resolved
- examples/interesting_deps/Package.swift
- examples/interesting_deps/main.swift
- examples/interesting_deps/swift_deps_index.json
- swiftpkg/internal/clang_files.bzl
- swiftpkg/internal/pkginfos.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/clang_files_tests.bzl
- Read and apply Cxx settings for Swift package targets.
- Consolidate the list of private includes for clang targets to smallest possible number by removing those with a common parent leaving the shortest of the common parent paths.
- Add [GEOSwift package](https://github.com/GEOSwift/GEOSwift) to the `interesting_deps` example.
Closes #674.
> fix: read and apply per target Cxx settings and consolidate private includes

- docs/faq.md
> docs: add question about rules_xcodeproj and spawn strategy

- README.md
- docs/README.md
- docs/legacy_quickstart.md
- Move legacy quickstart instructions to its own markdown file.
- Link to the legacy quickstart from the main README file.
- Update the docs README to contain a link to the legacy quickstart.
> docs: move legacy quickstart to its own file

- docs/internal_rules_and_macros_overview.md
- examples/firebase_example/MODULE.bazel
- examples/firebase_example/analytics/AnalyticsExample/BUILD.bazel
- examples/firebase_example/do_test
- swiftpkg/internal/generate_modulemap.bzl
- swiftpkg/internal/pkginfos.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
The goal of this PR is to selectively generate modulemap files for ObjC targets. If an ObjC target provides a modulemap, we will not generate a modulemap. This avoids `redefinition of module` errors when running outside of the Bazel action sandbox. While we may not generate modulemaps for some ObjC targets, we must continue to create the `generate_modulemap` targets. The logic that assigns dependencies has no way to know whether a modulemap target has been generated (i.e., the ObjC target may be a dependency in another Swift package). Hence, `generate_modulemap` has been modified to have a noop mode.
- Add `noop` attribute to `generate_modulemap` rule. If `True`, a modulemap is generated and the appropriate providers are populated. If `False, a modulemap is not generated and empty …
> fix: do not generate a modulemap for Objc targets, if they provide one

- swiftpkg/internal/artifact_infos.bzl
- swiftpkg/tests/BUILD.bazel
- swiftpkg/tests/artifact_infos_tests.bzl
- swiftpkg/tests/testutils.bzl
- The `find()` result for the file type results was broken. It was not detecting matches at the front of the string and it was not checking the dynamic result properly.
- Relaxed the static check to support additional file type results found in the wild.
- Add unit tests.
[Related Slack thread](https://bazelbuild.slack.com/archives/C05NZSHE7FU/p1698959858859589)
> fix: link type detection for frameworks

- README.md
Fixes the following minor issues:
- Remove `$` from code snippets currently copy-pasting a snippet would fail in the terminal since `$` would be copied.
- Use `bzl` code tag instead of `python` which seems to be supported by github
> fix: correct minor README.md issues

- bzlmod/workspace/Package.swift
- bzlmod/workspace/Sources/MyExecutable/BUILD.bazel
- bzlmod/workspace/Sources/MyExecutable/MyExecutable.swift
Extends the `MyExecutable` example to demonstrate a bug when `import RegexBuilder` is used. It seems to be unable to find the dependency label for `RegexBuilder` and then erroneously adds a dep for `"@swiftpkg_swift_argument_parser//:Plugins_GenerateManual"` which fails to build.
> chore: extend argument parser example

- .github/actions/configure_remote_cache_auth/action.yml
- .github/workflows/ci.yml
- shared.bazelrc
Copied over a change proposed in #740.
> fix: only configure remote cache if the API key is available

- bzlmod/workspace/Sources/MyExecutable/MyExecutable.swift
- gazelle/internal/swift/dependency_index.go
Works towards the issues in #742.
This particular bug can be seen when adding an `import` to a built-in framework when it is not already in the `builtin_modules.go` file.
For example, adding `import os` would warn with:
```
gazelle: Unable to find dependency labels for os
```
Which is correct **but** it would also erroneously add a dependency in the generated `BUILD.bazel` file for `@swiftpkg_swift_argument_parser//:Plugins_GenerateManual` which then fails the build entirely.
The reason for this bug is because the logic in `dependency_index.go` was not ensuring that the product being added as a dep was actually a product that needed to be resolved.
In the case where all modules are resolvable (i.e. all builtin frameworks accounted for) this isn't hit as the list of `modulesToResolve` is …
> fix: only add dependency when unresolved

- .github/actions/set_up_macos/action.yml
These are also occasionally timing out.
See the CI runs for https://github.com/cgrindel/rules_swift_package_manager/pull/755
Maybe Xcode 15.1 will improve things...
> chore: add more Xcode 14.3.1 CI exceptions

- swiftpkg/internal/swiftpkg_build_files.bzl
The `rules_swift` documentation clearly states that this attribute is only available on `swift_library`.
Closes #764.
> fix: only add `generates_header` attribute if target is a library

- config_settings/spm/platform/platforms.bzl
- config_settings/spm/tests/platform_tests/BUILD.bazel
- config_settings/spm/tests/platform_tests/platforms_tests.bzl
- examples/firebase_example/MODULE.bazel.lock
- swiftpkg/internal/bzl_selects.bzl
- swiftpkg/internal/pkginfos.bzl
Bazel currently does not support `maccatalyst` as a platform. We were mapping it to `ios` as they are Mac apps that use iOS frameworks. However, this can lead to warnings if define values exist with the same name mapped for `ios` and `maccatalyst` (e.g. Firebase).
This PR filters out `maccatalyst` conditions. 
Closes #801.
> fix: filter out `maccatalyst` SPM platform

- gazelle/config.go
- gazelle/internal/swiftcfg/swift_config.go
The `update-repos` mode writes the file creating it from scratch. This makes the plugin more tolerant to index format changes.
> fix: do not load the index file in the gazelle plugin if not in fix or update mode

- examples/pkg_manifest_minimal/MODULE.bazel
- examples/pkg_manifest_minimal/MODULE.bazel.lock
- examples/pkg_manifest_minimal/Package.swift
- examples/pkg_manifest_minimal/Sources/MyExecutable/BUILD.bazel
- examples/pkg_manifest_minimal/Sources/MyExecutable/MyExecutable.swift
- examples/pkg_manifest_minimal/swift_deps_index.json
- examples/pkg_manifest_minimal/third_party/MyAmazingModule/.gitignore
- examples/pkg_manifest_minimal/third_party/MyAmazingModule/Package.swift
- examples/pkg_manifest_minimal/third_party/MyAmazingModule/Sources/MyAmazingModule/MyAmazingModule.swift
- examples/pkg_manifest_minimal/third_party/MyAmazingModule/Tests/MyAmazingModuleTests/MyAmazingModuleTests.swift
- examples/pkg_manifest_minimal/third_party/NotThatAmazingModule/.gitignore
- examples/pkg_manifest_minimal/third_party/NotThatAmazingModule/Package.swift
- examples/pkg_manifest_minimal/third_party/NotThatAmazingModule/Sources/NotThatAmazingModule/NotThatAmazingModule.swift
- examples/pkg_manifest_minimal/third_party/NotThatAmazingModule/Tests/NotThatAmazingModuleTests/NotThatAmazingModuleTests.swift
- gazelle/internal/swiftpkg/package_info.go
- swiftpkg/internal/pkginfos.bzl
- swiftpkg/tests/pkginfo_ext_deps_tests.bzl
- swiftpkg/tests/pkginfo_target_deps_tests.bzl
- swiftpkg/tests/pkginfos_tests.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
A local Swift package could have local Swift packages. We need find those and include them in the list of dependencies.
- Incorporate @brentleyjones fix from #876 to better handle file system dependencies in the Starlark code.
- Update the Gazelle plugin's `update-repos` action to recursively find all of the file system dependencies.
- Add example of a local package that has a local package dependency to `pkg_manifest_minimal`. Thanks to @lucasmarcal-faire for providing a repro that was the basis for this modification.
Closes #868.
Closes #876.
> fix: recursively find all local Swift packages

- .bcr/presubmit.yml
The BCR now requires a Bazel version in the `presubmit.yml`.
Related to https://github.com/bazelbuild/bazel-central-registry/pull/1413.
> fix: add missing bazel version to BCR presubmit

- examples/nimble_example/MODULE.bazel.lock
- examples/nimble_example/Package.resolved
- examples/nimble_example/Sources/NimbleExample/BUILD.bazel
- examples/nimble_example/swift_deps_index.json
- swiftpkg/internal/pkginfos.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
Background: SPM always includes the developer search paths for compilation and linking. Now that `rules_swift` supports including these for non-test targets, we will enable this feature.
- Use `always_include_developer_search_paths` for generated `swift_library` targets.
- Remove check for `XCTest` imports. Previously, we would mark targets as `testonly = True` if `XCTest` imports were detected. With the `always_include_developer_search_paths` feature, this is no longer necessary.
Closes #791.
> chore: enable `always_include_developer_search_paths` for all `swift_library` targets in external Swift packages

- bzlmod/workspace/MODULE.bazel.lock
- bzlmod/workspace/Sources/MyExecutable/BUILD.bazel
- bzlmod/workspace/swift_deps_index.json
- examples/firebase_example/MODULE.bazel.lock
- examples/grpc_example/MODULE.bazel.lock
- examples/interesting_deps/MODULE.bazel.lock
- examples/ios_sim/MODULE.bazel.lock
- examples/lottie_ios_example/MODULE.bazel.lock
- examples/messagekit_example/MODULE.bazel.lock
- examples/nimble_example/MODULE.bazel.lock
- examples/objc_code/MODULE.bazel.lock
- examples/phone_number_kit/MODULE.bazel.lock
- examples/pkg_manifest_minimal/MODULE.bazel.lock
- examples/pkg_manifest_minimal/Package.resolved
- examples/pkg_manifest_minimal/swift_deps_index.json
- examples/resources_example/MODULE.bazel.lock
- examples/shake_ios_example/MODULE.bazel.lock
- examples/snapkit_example/MODULE.bazel.lock
- examples/soto_example/MODULE.bazel.lock
- examples/stripe_example/MODULE.bazel.lock
- examples/tca_example/MODULE.bazel.lock
- examples/vapor_example/MODULE.bazel.lock
- examples/vapor_example/swift/Package.resolved
- examples/vapor_example/swift/deps.bzl
- examples/vapor_example/swift/deps_index.json
- examples/xcmetrics_example/MODULE.bazel.lock
Ran the following script to ensure that all of the child workspaces are up-to-date:
```bash
#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"
do_test() {
local do_test_path="${1}"
local dir
dir="$( dirname "${do_test_path}" )"
echo >&2 "***** Processing" "${dir}"
cd "${dir}"
"./do_test"
bazel clean
}
do_test_paths=(
"${script_dir}/bzlmod/workspace/do_test"
"${script_dir}/examples/nimble_example/do_test"
"${script_dir}/examples/grpc_example/do_test"
"${script_dir}/examples/stripe_example/do_test"
"${script_dir}/examples/interesting_deps/do_test"
"${script_dir}/examples/vapor_example/do_test"
"${script_dir}/examples/resources_example/do_test"
"${script_dir}/examples/objc_code/do_test" …
```
> chore: ensure that all child workspaces use new product labels

- examples/resources_example/MODULE.bazel
- examples/resources_example/Sources/MyApp/BUILD.bazel
- examples/resources_example/Sources/MyApp/MyApp.swift
- examples/resources_example/swift/Package.resolved
- examples/resources_example/swift/Package.swift
- examples/resources_example/swift_deps_index.json
- swiftpkg/internal/artifact_infos.bzl
- Check frameworks that are provided as archive files (XXX.a). 
- See [xcframwork doc](https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle) for more information.
- Add [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk) to the `resources_example`. This package provides their frameworks as archive files.
Closes #968.
> fix: support xcframeworks that use archive files (XXX.a)

- .bcr/presubmit.yml
BCR presubmit fails if these values are not the same.
> fix: ensure Bazel version in .bazelverion matches BCR presubmit config

- swiftpkg/internal/repo_rules.bzl
Support authentication using `.netrc` file when downloading artifacts.
I copied the implementation from here: https://github.com/bazelbuild/bazel/pull/20915/files
> feat: Support netrc authentication

- swiftpkg/internal/ObjcResourceBundleAccessor.h.tmpl
This commit adds check for presence of ObjC support in currently used compiler. If not, skips SWIFTPM_MODULE_BUNDLE macros altogether.
fixes https://github.com/cgrindel/rules_swift_package_manager/issues/998
> fix: Added Obj-C support check in generated bundle header files

- swiftpkg/internal/build_files.bzl
We have a path that includes a unicode character and without this change the build file is being written with a very strangely encoded path.
According to the documentation the default is going to change soon: https://bazel.build/rules/lib/builtins/repository_ctx#file
> fix: Don't use legacy UTF8 handling when writing files

- gazelle/config.go
We should use the constant that we defined instead of a string in the switch statement.
> fix: use constants instead of string for directive names

- examples/resources_example/MODULE.bazel
- examples/resources_example/Sources/MyApp/BUILD.bazel
- examples/resources_example/Sources/MyApp/MyApp.swift
- examples/resources_example/Tests/MyAppTests/BUILD.bazel
- examples/resources_example/Tests/MyAppTests/MyAppTests.swift
- examples/resources_example/swift/Package.resolved
- examples/resources_example/swift/Package.swift
- examples/resources_example/swift_deps_index.json
- swiftpkg/internal/pkginfos.bzl
I'm not sure if this is the best solution, but it did solve my issues. Happy to discuss other approaches.
This is the error I'm seeing:
```
Traceback (most recent call last):
File "/private/var/tmp/_bazel_johnflanagan/c6ca44c5b5b4e1c56873b1d5235fffed/external/rules_apple~3.5.1/apple/internal/ios_rules.bzl", line 444, column 41, in _ios_application_impl
processor_result = processor.process(
File "/private/var/tmp/_bazel_johnflanagan/c6ca44c5b5b4e1c56873b1d5235fffed/external/rules_apple~3.5.1/apple/internal/processor.bzl", line 747, column 36, in _process
partial_outputs = [partial.call(p) for p in partials]
File "/private/var/tmp/_bazel_johnflanagan/c6ca44c5b5b4e1c56873b1d5235fffed/external/bazel_skylib~1.5.0/lib/partial.bzl", line 43, column 28, in _call
return …
```
> fix: don't include directories in resources

- tools/create_example/template_files/MODULE.bazel
Without this change I was getting the following error when creating new examples:
```
ERROR: /private/var/tmp/_bazel_johnflanagan/16c78d03b601ed18f3b30c014db2ef6d/external/rules_swift~~non_module_deps~build_bazel_rules_swift_local_config/BUILD:9:22: in xcode_swift_toolchain rule @@rules_swift~~non_module_deps~build_bazel_rules_swift_local_config//:toolchain:
Traceback (most recent call last):
File "/private/var/tmp/_bazel_johnflanagan/16c78d03b601ed18f3b30c014db2ef6d/external/rules_swift~/swift/internal/xcode_swift_toolchain.bzl", line 555, column 29, in _xcode_swift_toolchain_impl
target_triples.parse(cc_toolchain.target_gnu_system_name),
File "/private/var/tmp/_bazel_johnflanagan/16c78d03b601ed18f3b30c014db2ef6d/external/rules_swift~/swift/internal/target_triples.bzl", line 134, column …
```
> fix: add apple_support to create_example template

- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
In an attempt to localize defines to specific targets, we specify defines/macros for all target types (e.g., `swift_library`, `objc_library`, and `cc_library`) targets using  `copts`.
Fixes #1093.
> fix: specify all defines as local using `copts`

- .bcr/presubmit.yml
Need to synchronize the Bazel version in `.bazelversion` with the value in the presubmit YAML file.
> fix: synchronize the Bazel version for the BCR presubmit

- swiftpkg/internal/modulemap_parser/parser.bzl
- swiftpkg/internal/modulemap_parser/tokenizer.bzl
- swiftpkg/tests/modulemap_parser/tokenizer_tests.bzl
Fixes the tokenizer and modulemap parser to support C99 formatted comments. This is probably not amazing but we'll be able to move off this soon: https://github.com/bazelbuild/rules_swift/pull/1212
> fix: parsing modulemaps with comments

- gazelle/internal/spreso/pin.go
Addresses https://github.com/cgrindel/rules_swift_package_manager/issues/1059.
> feat: add support for `Package.resolved` version 3

- swiftpkg/internal/pkginfo_target_deps.bzl
- swiftpkg/tests/pkginfo_target_deps_tests.bzl
In the case of `accessibilitysnapshot`, it depends on `SnapshotTesting` by name. `SnapshotTesting` has an identity of `swift-snapshot-testing` (based on the git url, but it could be different for mirrors/forks), but the name is `snapshottesting`.
> fix: fix `byName` resolution

- README.md
I noticed that quickstart guide does not mention that users need to run `swift package resolve`prior to running `bazel mod tidy`.
> docs: update quickstart guide to include swift package manager command

- .bcr/presubmit.yml
The values need to match for BCR.
> fix: sync Bazel version with BCR presubmit

- docs/patch_swift_package.md
- swiftpkg/bzlmod/swift_deps.bzl
Update the Swift package patch instructions for bzlmod. Specifically, demonstrate how to specify the path using `swift_deps.configure_package()`.
> docs: update patch instructions for bzlmod

- README.md
Clarify when the `declare_swift_deps_info` attribute should be enabled for workspaces that use  `rules_swift_package_manager`.
Closes #1176.
> docs: clarify when to enable `declare_swift_deps_info`

- swiftpkg/internal/repository_utils.bzl
Ensure that the error message is created successfully regardless of the `xxx_ctx`.
Closes #1188.
> fix: avoid error when attempting to fail with after SPM command error

- do_renovate_post_upgrade
Apparently, `bazelisk` is no longer added to the PATH by npm install.
> fix: explicitly set the location of bazelisk

- swiftpkg/bzlmod/swift_deps.bzl
- swiftpkg/internal/pkginfos.bzl
This fixes an issue where if a brand new dependency is added to the `Package.swift` when `Package.resolved` has not yet been updated, the Bazel build fails. It fails because there is no `pin` available for the `source_control` dependency as the `Package.resolved` has not yet been updated.
For example, a command line tool built using `rules_swift_package_manager` which has a `Package.swift` for `swift-argument-parser`. If a new dependency is added to the `Package.swift` but not yet used in any of the Bazel targets and no `swift package resolve` has been run when a build is run the build will fail with:
```
File bazel-path/external/rules_swift_package_manager~/swiftpkg/bzlmod/swift_deps.bzl", line 152, column 25, in _declare_pkg_from_dependency
commit = pin.state.revision,
Error: 'NoneType' …
```
> fix: ignore unresolved packages in Package.swift

- MODULE.bazel
- deps.bzl
- docs/repository_rules_overview.md
- swiftpkg/bzlmod/swift_deps.bzl
- swiftpkg/internal/build_decls.bzl
- swiftpkg/internal/build_files.bzl
- swiftpkg/internal/pkginfos.bzl
- swiftpkg/internal/repo_rules.bzl
- swiftpkg/internal/repository_files.bzl
- swiftpkg/internal/starlark_codegen.bzl
- swiftpkg/internal/swift_package.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
> feat: set license information for packages with rules_license

- .bcr/presubmit.yml
The BCR version must match the version in `.bazelversion`.
> chore: update BCR Bazel version to match .bazelversion

- .bcr/presubmit.yml
Must be the same for BCR presubmit to succeed.
> chore: sync Bazel version in BCR presubmit

- docs/bzlmod_extensions_overview.md
- examples/interesting_deps/MODULE.bazel
- swiftpkg/internal/swift_package_tool.bzl
- swiftpkg/internal/swift_package_tool_repo.bzl
Sort of missed doing this in #1307 but it provides a nicer interface for users and will support the `dict` attr for the upcoming Swift Package Registry support.
> feat: support non-string attrs in swift_package_tool

- docs/bzlmod_extensions_overview.md
- examples/interesting_deps/MODULE.bazel
- swiftpkg/internal/swift_package_tool.bzl
- swiftpkg/internal/swift_package_tool_runner_template.sh
Add support for setting a custom `--security-path`. This also ensures the global path is not used.
> feat: set a default `--security-path` for swift_package_tool

- docs/faq.md
peak -> top of a mountain, while peek -> look into
> docs: update spelling error in faq.md

- docs/faq.md
- examples/firebase_example/.bazelrc
- examples/interesting_deps/BUILD.bazel
- examples/interesting_deps/MODULE.bazel
- examples/interesting_deps/Package.resolved
- examples/interesting_deps/Package.swift
- examples/interesting_deps/do_test
- examples/interesting_deps/objc_test.m
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
Fixes duplicate definition errors caused by custom/generated modulemap files.
> fix: correct issues with modulemap generation

- MODULE.bazel
- swiftpkg/internal/BUILD.bazel
- swiftpkg/internal/generate_modulemap.bzl
rules_swift will create a modulemap automatically unless the `SwiftInteropInfo` is suppressed. Since the `generate_modulemap` rule itself is a modulemap it should not have a modulemap generated for it.
> fix: suppress modulemap target via swift interop

- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
This matches SPM’s behavior. It’s needed to create dynamic frameworks from rspm targets.
> fix: set `alwayslink = True`

- swiftpkg/internal/repo_rules.bzl
The rules should ignore invalid `.xcframework` paths like SPM does ([see here](https://github.com/swiftlang/swift-package-manager/blob/c26c12f54357fb7246c0bdbe3483105389f056b8/Sources/Workspace/Workspace%2BBinaryArtifacts.swift#L771-L780)). Unlike SPM however, in Starlark we do not have a readily available `.plist` decoder so we will simply ensure that an `Info.plist` file exists and let the build rules handle potential issues.
This fixes cases where I was getting warnings because our .zip file contains a `__MACOSX` directory that contains a `.xcframework` directory (this is used for metadata by macOS). All the files are prefixed with `._` so the Info.plist check here fixes including these bad paths in our search.
```
DEBUG: /private/var/tmp/_bazel_lpadron/9ae9416857eb79bb978de35a53d54970/ …
```
> fix: Ignore invalid xcframework paths

- swiftpkg/internal/swiftpkg_build_files.bzl
Assembly files like `.S` are allowed in `srcs` of `objc_library` but we were dropping these because it was only being handled in the `else` case where we do not have Objective-C srcs.
A package that requires this change to build is: https://github.com/microsoft/plcrashreporter. I did not add an example of that here because it unfortunately still does not build in sandbox mode (because of issues with the `Package.swift` using `excludes`, I can work on updating the package and adding the example here at a later time).
[See this change for how it was done before we split the targets](https://github.com/cgrindel/rules_swift_package_manager/commit/6d12d535660958018f341cedfc567d1fd19a427a#diff-b4f84bf6654c556e5a44572cef98ce510f12dfea788eed39432b9af5f3e4559dL21)
> fix: Add missing assembly src files to ObjCxx

- swiftpkg/internal/bzl_selects.bzl
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/bzl_selects_tests.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
This primarily does two changes:
- Passes `-Xcc -DSWIFT_PACKAGE` for the Swift library target generated `copts` attribute.
- Removes de-duplication in `bzl_selects.bzl`
- Using `sets` enforces unique values for the fields which is problematic, for example: `copts = ["-DSWIFT_PACKAGE", "-Xcc", "-DSWIFT_PACKAGE"]` are valid copts but would get de-duplicated into `copts = ["-DSWIFT_PACKAGE", "-Xcc"]`.
- We should not work-around duplicated `deps`, `copts`, etc. in the `BUILD` file generator. If issues arise during the build the `Package.swift` for the package should be fixed if it is a legitimate duplicate.
Fixes #1259
> fix: usage of `copts` for `SWIFT_PACKAGE`

- examples/interesting_deps/BUILD.bazel
- examples/interesting_deps/MODULE.bazel
- examples/interesting_deps/Package.resolved
- examples/interesting_deps/Package.swift
- examples/interesting_deps/main.swift
Showcases an issue with `SWIFT_PACKAGE` defines when consuming a Swift Package like: https://github.com/luispadron/swift-package-defines-example
The package above builds with `swift build` but fails when building through Bazel in the added example (without #1260)
```sh
cd examples/interesting_deps && bazel build print
ERROR: 
...
external/rules_swift_package_manager~~swift_deps~swiftpkg_swift_package_defines_example/Sources/FooSwift/Foo.swift:5:24: error: cannot find 'foo' in scope
3 | public func fooSwift() {
4 |     print("FooSwift")
5 |     print("ObjC foo: \(foo())")
|                        `- error: cannot find 'foo' in scope
6 | }
7 | 
```
> chore: add example of SWIFT_PACKAGE defines

- swiftpkg/internal/pkginfos.bzl
- swiftpkg/internal/repository_files.bzl
This PR adds an `exclude_directories` argument to `repository_files.list_files_under` which resulted in a massive performance improvement for packages with lots of resources.
I noticed that it was taking a really long time to "fetch" a package that was local to my machine, so there was no actual network operations required.
I dug into the issue and it's actually from a change I added in [this PR](https://github.com/cgrindel/rules_swift_package_manager/pull/1039) to expand certain types of resources into a list of their assets. The overwhelming majority of the time was being spent on the `if not repository_files.is_directory(repository_ctx, p)` check inside of the loop. By omitting directories from the result of `list_files_under` we can skip all of that work.
I didn't see any uses of …
> fix: Optionally exclude directories from list_files_under for performance

- swiftpkg/bzlmod/swift_deps.bzl
- swiftpkg/internal/local_swift_package.bzl
Call `repository_ctx.watch_tree` to ensure that repositories are refetched for local SPM packages if new files are added or removed. This will also cause a refetch if a file's content changes, but I didn't see a way to only watch for changes to file creation/deletion.
Without this I was experiencing issues where local SPM packages would fail to compile after pulling down changes from git because new files were added without the repo's `BUILD.bazel` file being updated as well.
> fix: watch local packages to refetch if files are added/updated

- .github/workflows/ci.yml
- MODULE.bazel
- examples/firebase_example/MODULE.bazel
- examples/ios_sim/MODULE.bazel
This version of `bazel-starlib` supports organized release notes.
> chore: upgrade `bazel-starlib` to 0.26.0 for organized release notes

- .github/actions/set_up_macos/action.yml
> fix: use Xcode 16.3 to address failures on macos-15 GH runner

- .github/actions/tidy_and_test/action.yml
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
For SPM modules that use precompiled resource bundles (i.e `.bundle` files), Bazel throws the warning
```
WARNING: input 'Sources/Down/Resources/DownView (macOS).bundle' is a directory; dependency checking of directories is unsound
```
Instead of just referencing the `.bundle` path directly we should wrap it in a `apple_bundle_import` for the prebuilt bundle and then add it into the `resources` attr.
> fix: precompiled resource bundle warnings

- .github/actions/set_up_ubuntu/action.yml
- .github/workflows/ci.yml
- examples/vapor_example/do_test
- swiftpkg/internal/swift_package_tool_runner_template.sh
The Renovate runs have been failing when trying to run `//:update_swift_packages` on modified workspaces. The issue is that the Swift worker processes behave differently on MacOS vs Linux. On MacOS, the arguments are essentially passed through to `xcrun`. On Linux, it is more of a barebones process runner.
Previously, we expected the worker to find `swift` automatically. This does not work on Linux. This PR adds logic to find `swift` by attempting to ask the worker. If that fails, fall back to looking in the `PATH`.
I also upgraded Swift to 6.1 on Ubuntu.
Closes #1591.
> fix: `swift_package_tool` so that it works on Linux and MacOS

- config_settings/bazel/compilation_mode/compilation_modes.bzl
- swiftpkg/internal/BUILD.bazel
- swiftpkg/internal/swiftpkg_build_files.bzl
- swiftpkg/tests/swiftpkg_build_files_tests.bzl
SPM conditionally defines `DEBUG=1` for Clang targets. We should too.
```swift
/// A list of compilation conditions to enable for conditional compilation expressions.
private var activeCompilationConditions: [String] {
var compilationConditions = ["-DSWIFT_PACKAGE=1"]
switch buildParameters.configuration {
case .debug:
compilationConditions += ["-DDEBUG=1"]
case .release:
break
}
return compilationConditions
}
```
https://github.com/swiftlang/swift-package-manager/blob/2b0505e24798468102e9ec1937bb485346c59695/Sources/Build/BuildDescription/ClangModuleBuildDescription.swift#L448-L459
This was causing a linker issue in debug for InjectionNext which relies on DEBUG to conditionally include/exclude chunks of code in a C file with SPM …
> fix: Define DEBUG for Clang targets in dbg

- swiftpkg/internal/swift_package.bzl
Support https://bazel.build/reference/command-line-reference#common_options-flag--repo_contents_cache.
> feat: add support for `--repo_contents_cache`

- config_settings/bazel/apple_platform_type/BUILD.bazel
- config_settings/bazel/compilation_mode/BUILD.bazel
- config_settings/spm/configuration/BUILD.bazel
- config_settings/spm/platform/BUILD.bazel
- config_settings/spm/platform_configuration/BUILD.bazel
I added `package(default_visibility = ["//visibility:public"])` to the `compilation_mode` package so its behavior matches the other `//config_settings/...` packages that already declare a public default.
Follow-up to discuss: should we add `--incompatible_config_setting_private_default_visibility` or `--incompatible_enforce_config_setting_visibility` to `.bazelrc`, I'm not sure if this could have unwanted effects.
fixes: #1715
> fix: set default visibility to public
